version: "3.2"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "48080:8080"
    # links:
    #   - mongo
    networks: 
      - docker-api-plate
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks: 
  #     - docker-api-plate

networks: 
  docker-api-plate:
    driver: 
      bridge